
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'

Style/ConditionalAssignment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/WordArray:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/SignalException:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/MethodMissingSuper:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 150
Style/EmptyMethod:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false 
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys: 
  Enabled: false
Style/HashTransformValues: 
  Enabled: false
Layout/Tab:
  Enabled: false